/**
 * Regression guardrail for issue #199 (guardrail b): for every year
 * 2019-2025, count(name-derived divided) must equal count(tally-derived
 * divided) - AND both must equal the absolute count confirmed by an
 * independent walk of the raw data/*.json roll calls (issue #199
 * verification): 310/289/287/176/382/541/540 for 2019-2025 respectively.
 *
 *   - name-derived divided: a motion with at least one named voter in its
 *     `nays` array (fusion-repaired per PR #197/#201, so this is the
 *     genuine per-councillor Nay count, not an artifact of a comma-joined
 *     voter cell being read as one name).
 *   - tally-derived divided: a motion whose eSCRIBE-published result
 *     string carries a "(N to M)" tally where M (the second number) is
 *     non-zero.
 *
 * These are two independent signals derived from the same underlying
 * eSCRIBE page (the per-row voter list vs. the printed summary tally).
 * The identity holds EXACTLY at the raw roll-call level; it previously
 * held only approximately (308/287/286/176/382/539/537, with 2023 and
 * 2025 off by one) in the shipped data/votes/_all-motions.json, because
 * motionKey there omitted rollCallOrdinal for 2018+ dates, so a handful of
 * genuinely distinct roll calls under one item merged into one stored
 * record that inherited the FIRST roll call's tally while absorbing the
 * SECOND roll call's nay voters (issue #199 d3, not actually pre-2018-
 * specific - see the motionKey comment in generate-votes.ts). Once
 * rollCallOrdinal is part of the 2018+ key too, the two absolute-count
 * assertions below hold with zero exceptions - this is a stronger, and
 * simpler, guarantee than "modulo known exceptions", so it's asserted
 * directly rather than inferred from the mismatch-count check alone.
 *
 * 2018 is a known transition year (mixed eSCRIBE/Word-format minutes
 * mid-year) and is deliberately excluded from this oracle, same as the
 * issue #199 investigation scoped it.
 *
 * The two named exceptions this oracle originally shipped with
 * ("2023-07-17|3.5", "2025-06-03|8.3.16") were an artifact of the
 * motionKey dedup-key collision fixed alongside this oracle (issue #199
 * d3/d6, rollCallOrdinal now part of the 2018+ key) - once that landed,
 * the identity holds with ZERO exceptions (see the absolute-count
 * assertions below, confirmed against an independent walk of the raw
 * data/*.json roll calls). Keeping a "modulo known exceptions" escape
 * hatch around a check that no longer needs one is exactly the kind of
 * thing that quietly reabsorbs a real future regression as a "known"
 * exception - deleted (issue #199 punch list item 3). Any mismatch now
 * fails the test, full stop.
 *
 * Run: npx tsx --test scripts/generate-votes-identity-oracle.test.ts
 * (Requires data/votes/_all-motions.json to have been regenerated by
 * `npx tsx scripts/generate-votes.ts` from the current data/ directory.)
 */

import test, { describe, before } from "node:test"
import assert from "node:assert"
import fs from "fs/promises"
import path from "path"

interface Motion {
  id: string
  date: string
  itemNumber: string
  result: string
  nays: string[]
}

interface AllMotionsFile {
  motions: Motion[]
}

// Absolute name-derived (== tally-derived, exactly - see the module doc
// comment. A regression that dropped N divided motions from BOTH signals
// equally would still satisfy "the two signals agree with each other", so
// this absolute check is required to actually catch a coverage
// regression, not just a fusion (name-vs-tally disagreement) regression.
const EXPECTED_DIVIDED_COUNTS: Record<string, number> = {
  "2019": 310,
  "2020": 289,
  "2021": 287,
  "2022": 176,
  "2023": 382,
  "2024": 541,
  "2025": 540,
}

const ORACLE_YEARS = ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]

describe("generate-votes.ts: 2019-2025 name-vs-tally divided identity oracle (issue #199 guardrail b)", () => {
  let motions: Motion[]

  before(async () => {
    const motionsPath = path.join(process.cwd(), "data", "votes", "_all-motions.json")
    const raw = await fs.readFile(motionsPath, "utf-8")
    motions = (JSON.parse(raw) as AllMotionsFile).motions
  })

  test("regenerated corpus actually contains motions for each oracle year (sanity check on the fixture itself)", () => {
    const yearsPresent = new Set(motions.map(m => m.date.slice(0, 4)))
    for (const year of ORACLE_YEARS) {
      assert.ok(yearsPresent.has(year), `expected at least one ${year} motion in data/votes/_all-motions.json`)
    }
  })

  for (const year of ORACLE_YEARS) {
    test(`${year}: count(name-derived divided) === count(tally-derived divided), exactly`, () => {
      let nameCount = 0
      let tallyCount = 0
      const mismatches: string[] = []

      for (const m of motions) {
        if (m.date.slice(0, 4) !== year) continue

        const nameDivided = m.nays.length > 0
        const tallyMatch = m.result.match(/\((\d+) to (\d+)\)/)
        const tallyDivided = !!tallyMatch && tallyMatch[2] !== "0"

        if (nameDivided) nameCount++
        if (tallyDivided) tallyCount++

        if (nameDivided !== tallyDivided) {
          mismatches.push(`item ${m.itemNumber} (id ${m.id}, date ${m.date}): name=${nameDivided} tally=${tallyDivided}, result=${JSON.stringify(m.result)}`)
        }
      }

      assert.strictEqual(
        mismatches.length,
        0,
        `unexpected name-vs-tally mismatch(es) in ${year} - a fusion or coverage regression (see issue #199):\n` +
          mismatches.join("\n")
      )

      // The two counts must match EXACTLY now (issue #199 punch list item
      // 3 - see the module doc comment for why the old "modulo known
      // exceptions" slack is gone). This is the actual canary: any NEW
      // disagreement fails via the per-motion assertion above already, so
      // this is a belt-and-suspenders total-count check.
      assert.strictEqual(
        nameCount,
        tallyCount,
        `${year}: name=${nameCount} tally=${tallyCount} - the two signals must agree exactly`
      )

      // Absolute count check (issue #199 verification finding: the
      // mismatch-count check above can't see a coverage regression that
      // drops N divided motions from both signals equally - only an
      // absolute check against the independently-confirmed raw count can).
      assert.strictEqual(
        nameCount,
        EXPECTED_DIVIDED_COUNTS[year],
        `${year}: name-derived divided count is ${nameCount}, expected exactly ${EXPECTED_DIVIDED_COUNTS[year]} (issue #199's independently-confirmed raw-roll-call count) - a coverage regression, not just a fusion mismatch`
      )
    })
  }
})
