/**
 * Regression test for the "recuse mislabeled as absent" bug.
 *
 * Ground truth (verified directly against the raw meeting data in
 * data/2026-07/2026-07-21 12th Meeting of Council.json): Councillor
 * P. Van Meerbergen declared a pecuniary interest and recused himself from
 * four votes at the 2026-07-21 "12th Meeting of Council":
 *   - Item 8.4.5 (Child Care and Early Years - Engagement of Auditor Services)
 *   - Item 13, Bill No. 267 (three readings: First, Second, Third/Enactment)
 *
 * Before the fix, scripts/generate-votes.ts collapsed every non-yea/nay row
 * (recuse, conflict, abstain, and real scraper noise) into "absent". This
 * test locks in that recusals are now classified as "recuse" and are
 * excluded from the "absent" bucket, using the ACTUAL regenerated
 * data/votes/p-van-meerbergen.json (not a synthetic fixture) so it will
 * catch a regression in either the classifier or the regeneration
 * pipeline.
 *
 * Run: npx tsx --test scripts/generate-votes.test.ts
 * (Requires data/votes/p-van-meerbergen.json to have been generated by
 * `npx tsx scripts/generate-votes.ts` from the current data/ directory.)
 */

import test, { describe, before } from "node:test"
import assert from "node:assert"
import fs from "fs/promises"
import path from "path"
import { classifyVoteType } from "../lib/votes/vote-type.js"

interface VoteRecord {
  date: string
  itemNumber: string
  itemTitle: string
  motionText: string
  vote: string
}

interface CouncillorVotesFile {
  councillor: string
  slug: string
  summary: {
    totalVotes: number
    yeas: number
    nays: number
    absent: number
    recuse: number
    abstain: number
    other: number
  }
  votes: VoteRecord[]
}

describe("generate-votes.ts: recuse/conflict/abstain vs absent (2026-07-21 Council meeting)", () => {
  let votesFile: CouncillorVotesFile

  before(async () => {
    const votesPath = path.join(process.cwd(), "data", "votes", "p-van-meerbergen.json")
    const raw = await fs.readFile(votesPath, "utf-8")
    votesFile = JSON.parse(raw)
  })

  test("raw meeting data still contains the expected Bill No. 267 recusal rows (sanity check on the fixture itself)", async () => {
    const meetingPath = path.join(
      process.cwd(),
      "data",
      "2026-07",
      "2026-07-21 12th Meeting of Council.json"
    )
    const meeting = JSON.parse(await fs.readFile(meetingPath, "utf-8"))
    const item13 = meeting.items["13"]
    assert.ok(item13, "expected item 13 (By-laws) to exist in the raw meeting data")

    const bill267Rows = item13.content.filter((c: { motion_texts?: { string: string }[] }) =>
      c.motion_texts?.some(t => t.string.includes("Bill No. 267"))
    )
    assert.strictEqual(bill267Rows.length, 3, "expected 3 readings of Bill No. 267")

    for (const row of bill267Rows) {
      const voteRow = row.vote.rows.find((r: { voters: string[] }) =>
        r.voters.some((v: string) => v.includes("Van Meerbergen"))
      )
      assert.ok(voteRow, "expected a vote row naming Van Meerbergen")
      assert.strictEqual(voteRow.vote, "Recuse:", "raw label must be 'Recuse:' for this to be a valid regression fixture")
    }
  })

  test("Van Meerbergen's Bill No. 267 votes (all 3 readings) are classified as 'recuse', not 'absent'", () => {
    const bill267Votes = votesFile.votes.filter(
      v => v.date === "2026-07-21" && v.motionText.includes("Bill No. 267")
    )
    assert.strictEqual(bill267Votes.length, 3, "expected 3 Bill No. 267 vote records for Van Meerbergen")
    for (const v of bill267Votes) {
      assert.strictEqual(
        v.vote,
        "recuse",
        `Bill No. 267 vote (item ${v.itemNumber}) must be classified as "recuse", not "${v.vote}"`
      )
    }
  })

  test("Van Meerbergen's Child Care/Auditor Services recusal (item 8.4.5) is classified as 'recuse', not 'absent'", () => {
    const match = votesFile.votes.find(
      v => v.date === "2026-07-21" && v.itemNumber === "8.4.5"
    )
    assert.ok(match, "expected a vote record for item 8.4.5 on 2026-07-21")
    assert.strictEqual(match!.vote, "recuse")
  })

  test("none of Van Meerbergen's 2026-07-21 votes are misclassified as absent", () => {
    const votesOnDate = votesFile.votes.filter(v => v.date === "2026-07-21")
    const wronglyAbsent = votesOnDate.filter(
      v => v.vote === "absent" && v.itemTitle && (v.motionText.includes("Bill No. 267") || v.itemNumber === "8.4.5")
    )
    assert.strictEqual(wronglyAbsent.length, 0, "no recusal should ever appear as 'absent'")
  })

  test("summary.recuse is tracked separately and summary.absent no longer includes recusals", () => {
    assert.ok(votesFile.summary.recuse > 0, "expected a nonzero recuse count in the summary")
    // Cross-check: total votes must still reconcile across all buckets.
    const { yeas, nays, absent, recuse, abstain, other, totalVotes } = votesFile.summary
    assert.strictEqual(
      yeas + nays + absent + recuse + abstain + other,
      totalVotes,
      "yea+nay+absent+recuse+abstain+other must reconcile to totalVotes"
    )
  })

  test("classifyVoteType direct check on the exact raw label used in this meeting", () => {
    assert.strictEqual(classifyVoteType("Recuse:"), "recuse")
  })
})
