/**
 * Regression guardrail for issue #199 (guardrail b): for every year
 * 2019-2025, count(name-derived divided) must equal count(tally-derived
 * divided).
 *
 *   - name-derived divided: a motion with at least one named voter in its
 *     `nays` array (fusion-repaired per PR #197/#201, so this is the
 *     genuine per-councillor Nay count, not an artifact of a comma-joined
 *     voter cell being read as one name).
 *   - tally-derived divided: a motion whose eSCRIBE-published result
 *     string carries a "(N to M)" tally where M (the second number) is
 *     non-zero.
 *
 * These are two independent signals derived from the same underlying
 * eSCRIBE page (the per-row voter list vs. the printed summary tally).
 * Confirmed exact for 2019-2022, 2024 and 2026 against the current
 * regenerated corpus; a real fusion or coverage regression (the two
 * failure modes issue #199 investigated) would move this identity, which
 * is exactly why it's asserted as a canary here, per-year, not as one
 * combined total that could hide a one-year regression inside
 * flat-overall numbers.
 *
 * 2023 and 2025 each carry ONE pre-existing exception, present before any
 * of the issue #199 fixes and unrelated to them (confirmed via a
 * before/after diff against the pre-fix _all-motions.json: identical in
 * both states) - an eSCRIBE-published "(N to 0)" tally alongside a
 * recorded dissenting voter, i.e. a genuine tally-vs-voter-list
 * disagreement on THIS axis, distinct from the Yeas>Nays-vs-Passed/Failed
 * axis scraping/verify_vote_tallies.py already tracks known anomalies
 * for. Named explicitly below (same convention as that script's
 * KNOWN_SUPERMAJORITY_EXCEPTIONS), not silently absorbed - flagged for
 * follow-up, not fixed here (out of scope for this PR).
 *
 * 2018 is a known transition year (mixed eSCRIBE/Word-format minutes
 * mid-year) and is deliberately excluded from this oracle, same as the
 * issue #199 investigation scoped it.
 *
 * Run: npx tsx --test scripts/generate-votes-identity-oracle.test.ts
 * (Requires data/votes/_all-motions.json to have been regenerated by
 * `npx tsx scripts/generate-votes.ts` from the current data/ directory.)
 */

import test, { describe, before } from "node:test"
import assert from "node:assert"
import fs from "fs/promises"
import path from "path"

interface Motion {
  id: string
  date: string
  itemNumber: string
  result: string
  nays: string[]
}

interface AllMotionsFile {
  motions: Motion[]
}

// (year, itemNumber) pairs known, ahead of time, to disagree between the
// two signals - see the module doc comment above for why each is not a
// regression.
const KNOWN_TALLY_VS_VOTER_LIST_EXCEPTIONS = new Set([
  "2023|3.5", // 2023-07-17 "Motion Passed (5 to 0)" with a recorded Nay voter
  "2025|8.3.16", // 2025-06-03 "Motion Passed (14 to 0)" with a recorded Nay voter
])

const ORACLE_YEARS = ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]

describe("generate-votes.ts: 2019-2025 name-vs-tally divided identity oracle (issue #199 guardrail b)", () => {
  let motions: Motion[]

  before(async () => {
    const motionsPath = path.join(process.cwd(), "data", "votes", "_all-motions.json")
    const raw = await fs.readFile(motionsPath, "utf-8")
    motions = (JSON.parse(raw) as AllMotionsFile).motions
  })

  test("regenerated corpus actually contains motions for each oracle year (sanity check on the fixture itself)", () => {
    const yearsPresent = new Set(motions.map(m => m.date.slice(0, 4)))
    for (const year of ORACLE_YEARS) {
      assert.ok(yearsPresent.has(year), `expected at least one ${year} motion in data/votes/_all-motions.json`)
    }
  })

  for (const year of ORACLE_YEARS) {
    test(`${year}: count(name-derived divided) === count(tally-derived divided), modulo known exceptions`, () => {
      let nameCount = 0
      let tallyCount = 0
      const mismatches: string[] = []

      for (const m of motions) {
        if (m.date.slice(0, 4) !== year) continue

        const nameDivided = m.nays.length > 0
        const tallyMatch = m.result.match(/\((\d+) to (\d+)\)/)
        const tallyDivided = !!tallyMatch && tallyMatch[2] !== "0"

        if (nameDivided) nameCount++
        if (tallyDivided) tallyCount++

        if (nameDivided !== tallyDivided) {
          const key = `${year}|${m.itemNumber}`
          if (!KNOWN_TALLY_VS_VOTER_LIST_EXCEPTIONS.has(key)) {
            mismatches.push(`item ${m.itemNumber} (id ${m.id}): name=${nameDivided} tally=${tallyDivided}, result=${JSON.stringify(m.result)}`)
          }
        }
      }

      assert.strictEqual(
        mismatches.length,
        0,
        `unexpected name-vs-tally mismatch(es) in ${year} - a fusion or coverage regression (see issue #199):\n` +
          mismatches.join("\n")
      )

      // The two counts, once the known exceptions are set aside on both
      // sides, must land within the known-exception count of each other -
      // this is the actual canary: any NEW disagreement beyond the two
      // named exceptions fails via the assertion above, so this is a
      // belt-and-suspenders total-count check.
      const knownExceptionsThisYear = [...KNOWN_TALLY_VS_VOTER_LIST_EXCEPTIONS].filter(k =>
        k.startsWith(`${year}|`)
      ).length
      assert.ok(
        Math.abs(nameCount - tallyCount) <= knownExceptionsThisYear,
        `${year}: name=${nameCount} tally=${tallyCount} differ by more than the ${knownExceptionsThisYear} known exception(s)`
      )
    })
  }
})
